// Nombres amigables para módulos
export const moduleNames: Record<string, string> = {
  'gestion-comercial-e-inventario': '🏪 Gestión Comercial e Inventario',
  'facturacion-electronica': '📄 Facturación Electrónica',
  'gestion-contable-y-financiera': '💰 Gestión Contable y Financiera',
  'reportes': '📊 Reportes',
  'configuracion': '⚙️ Configuración',
  'producto': '📦 Productos',
  'venta': '🛒 Ventas',
  'compra': '🛍️ Compras',
  'cliente': '👥 Clientes',
  'proveedor': '🏢 Proveedores',
  'marca': '🏷️ Marcas',
  'categoria': '📑 Categorías',
  'almacen': '🏭 Almacenes',
  'ubicacion': '📍 Ubicaciones',
  'unidad-medida': '📏 Unidades de Medida',
  'unidad-derivada': '🔢 Unidades Derivadas',
  'ingreso-salida': '↔️ Ingresos y Salidas',
  'tipo-ingreso-salida': '📋 Tipos de Ingreso/Salida',
  'usuario': '👤 Usuarios',
  'recepcion-almacen': '📥 Recepción de Almacén',
  'caja': '💵 Cajas',
  'caja-principal': '🏦 Cajas Principales',
  'sub-caja': '💳 Sub-Cajas',
  'transaccion-caja': '💸 Transacciones de Caja',
  'egreso-dinero': '💸 Egresos de Dinero',
  'despliegue-de-pago': '💳 Métodos de Pago',
  'cotizacion': '📝 Cotizaciones',
  'guia': '🚚 Guías de Remisión',
  'detalle-de-precios': '💲 Detalle de Precios',
}
