import { StyleSheet } from '@react-pdf/renderer'

export const styles_docs = StyleSheet.create({
  header: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  headerDocument: {
    maxWidth: 200,
    fontSize: 12,
    display: 'flex',
    gap: 4,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '4px 12px',
    borderRadius: '14px',
    border: '1.5px solid #fadc06',
  },
  headerDatosEmpresa: {
    fontSize: 7,
    textAlign: 'center',
    maxWidth: 130,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  headerTitle: {
    textAlign: 'center',
    fontWeight: 'bold',
    marginBottom: 4,
    marginTop: 4,
    padding: '4px 6px',
    textTransform: 'uppercase',
    backgroundColor: '#fadc06',
  },
  section: {
    marginBottom: 12,
  },
  sectionInformacionGeneral: {
    padding: '4px 8px',
    fontSize: 7,
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    width: '100%',
    border: '1.5px solid #fadc06',
    borderRadius: '4px',
  },
  titleSectionInformacionGeneral: {
    paddingLeft: 8,
    paddingTop: 4,
    paddingBottom: 2,
    display: 'flex',
    fontSize: 9,
    fontWeight: 'bold',
  },
  sectionInformacionGeneralColumn: {
    display: 'flex',
    flexDirection: 'column',
    width: '50%',
    gap: '2px',
  },
  subSectionInformacionGeneral: {
    display: 'flex',
    flexDirection: 'row',
    gap: '8px',
    width: '100%',
  },
  textTitleSubSectionInformacionGeneral: {
    width: '50%',
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  textValueSubSectionInformacionGeneral: {
    width: '50%',
  },
  tableHeader: {
    fontSize: 9,
    display: 'flex',
    flexDirection: 'row',
    borderBottom: '1px solid #fadc06',
    fontWeight: 'bold',
    backgroundColor: '#fadc06',
    borderTopLeftRadius: '4px',
    borderTopRightRadius: '4px',
    color: '#000',
    paddingVertical: 2,
  },
  tableRow: {
    display: 'flex',
    flexDirection: 'row',
    borderBottom: '1px solid #fadc06',
    paddingVertical: 2,
    fontSize: 8,
  },
  total: {
    fontSize: 8,
    textAlign: 'right',
    paddingRight: 4,
    border: '1px solid #fadc06',
    borderTop: 'none',
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 24,
  },
  textTotal: {
    backgroundColor: '#fadc06',
    paddingRight: 32,
    paddingLeft: 32,
    paddingTop: 2,
    paddingBottom: 2,
    fontWeight: 'bold',
  },
  observaciones: {
    fontSize: 8,
    textAlign: 'right',
    padding: '4px 12px',
    border: '1px solid #fadc06',
    borderRadius: '4px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 2,
  },
})
