export enum QueryKeys {
  MARCAS = 'marcas',
  ALMACENES = 'almacenes',
  UNIDADES_MEDIDA = 'unidades_medida',
  CATEGORIAS = 'categorias',
  UBICACIONES = 'ubicaciones',
  UNIDADES_DERIVADAS = 'unidades_derivadas',
  PRODUCTOS = 'productos',
  PRODUCTOS_SEARCH = 'productos_search',
  PRODUCTOS_TABLE_SEARCH = 'productos_table_search',
  PROVEEDORES = 'proveedores',
  PROVEEDORES_SEARCH = 'proveedores_search',
  TIPOS_INGRESO_SALIDA = 'tipos_ingreso_salida',
  USUARIOS = 'usuarios',
  COMPRAS = 'compras',
  COMPRAS_ANULADAS = 'compras_anuladas',
  COMPRAS_EN_ESPERA = 'compras_en_espera',
  RECEPCIONES_ALMACEN = 'recepciones_almacen',
  EGRESOS_DINERO = 'egresos_dinero',
  DESPLIEGUE_DE_PAGO = 'despliegue_de_pago',
  CLIENTES = 'clientes',
  CLIENTES_SEARCH = 'clientes_search',
  VENTAS = 'ventas',
  ENTREGAS_PRODUCTOS = 'entregas_productos',
  TIPO_CAMBIO = "TIPO_CAMBIO",
  COTIZACIONES = 'cotizaciones',
}
