export enum QueryKeys {
  MARCAS = 'marcas',
  ALMACENES = 'almacenes',
  UNIDADES_MEDIDA = 'unidades_medida',
  CATEGORIAS = 'categorias',
  UBICACIONES = 'ubicaciones',
  UNIDADES_DERIVADAS = 'unidades_derivadas',
  PRODUCTOS = 'productos',
  PRODUCTOS_SEARCH = 'productos_search',
  PRODUCTOS_TABLE_SEARCH = 'productos_table_search',
  PROVEEDORES = 'proveedores',
  PROVEEDORES_SEARCH = 'proveedores_search',
  TIPOS_INGRESO_SALIDA = 'tipos_ingreso_salida',
  USUARIOS = 'usuarios',
  COMPRAS = 'compras',
  RECEPCIONES_ALMACEN = 'recepciones_almacen',
}
